### PR TITLE
Fix-[Client/Server] Cyr not working

### LINKED ISSUE #7: [Client/Server] Cyr not working
## Description
**Cyr** encryption works on console but fails in Client/Server.

## Steps to Reproduce the Problem

  1. Send a message cyphered with cyr through the client.
  2. :boom: 

## Expected Behavior
Get the proper encrypted/decrypted message.

## Reproduces how often: [What percentage of the time does it reproduce?]
Every time.

## Additional info
Related to #8.

### PR DESCRIPTION
**Pull request by dtoniuc**
#### What does this PR do?
In the communication between client and server the data is trimmed. The error is caused because an incorect length is specified when the DatagramPacket is created. The code before fix used the length of the data string. This did not match the length of the byte array which is actually transmitted. This has been fixed by using the correct length in the DatagramPacket constructor.

#### Where should the reviewer start?
All the usage of DatagramPacket constructor in the CryptoClient.java and CryptoServer.java

#### How should this be manually tested?
1. Test Cyr encrypt/decrypt in Client/Server mode. Now no exception is thrown

#### Any background context you want to provide?
The string.getBytes() might have a different length than the actual string.

#### What are the relevant tickets?
Closes #7 

#### Screenshots
None

#### Questions
None

### CODE REVIEW

File: JEasyCryptoClient/src/CryptoClient.java [hunk 1]
```diff
@@ -149,7 +150,8 @@ private void handleEncryptRequest() throws IOException {
 		request.put("method", method);
 		request.put("data", text);
 		String data = request.toJSONString();
-		DatagramPacket packet = new DatagramPacket(data.getBytes(), data.length(), serverAddr, serverPort);
+		byte[] serializedData = data.getBytes(StandardCharsets.UTF_16);
```
Comment (a-rmz) [inline JEasyCryptoClient/src/CryptoClient.java]: For curiosity, any specific reason to use `UTF16` instead of `UTF8`?

File: JEasyCryptoClient/src/ResponseReader.java [hunk 2]
```diff
@@ -27,7 +28,7 @@ public void run() {
 				System.out.println("Starting to receive responses...");
 				socket.receive(packet);
 				System.out.println("Response received.");
-				String receivedData = new String(packet.getData(), 0, packet.getLength());
+				String receivedData = new String(packet.getData(), 0, packet.getLength(),StandardCharsets.UTF_16);
```
Comment (a-rmz) [inline JEasyCryptoClient/src/ResponseReader.java]: Can you please add a space after the comma to maintain style?

File: JEasyCryptoClient/src/CryptoClient.java (hunk 1 above)
Comment (dtoniuc) [reply JEasyCryptoClient/src/CryptoClient.java]: No, it can be any Unicode encoding as long as it is consistently used in code. Maybe UTF-8 is better because it uses less bytes.

File: JEasyCryptoClient/src/ResponseReader.java (hunk 2 above)
Comment (dtoniuc) [reply JEasyCryptoClient/src/ResponseReader.java]: Yes

File: JEasyCryptoClient/src/CryptoClient.java (hunk 1 above)
Comment (a-rmz) [reply JEasyCryptoClient/src/CryptoClient.java]: It's okay, I think that since we actually represent the serialized data as Strings, it's okay using UTF-16 in case the encryption algorithm makes weird offsets and returns even weirder characters.

File: JEasyCryptoClient/src/ResponseReader.java (hunk 2 above)
Comment (dtoniuc) [reply JEasyCryptoClient/src/ResponseReader.java]: Fixed

**Comment by a-rmz** [comment]
:shipit:
